[phases.setup]
cmds = [
    "echo 'Installing Java 17...'",
    "nix-env -iA nixpkgs.jdk17",
    "echo 'Installing Node.js...'",
    "nix-env -iA nixpkgs.nodejs-18_x"
]

[phases.build]
cmds = [
    "cd backend && mvn clean package -DskipTests",
    "cd ../frontend && npm install && npm run build"
]

[phases.start]
cmd = "java -jar backend/target/*.jar"